BEGIN TRANSACTION;

INSERT INTO public.users(username,password_hash,role) VALUES ('user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'ROLE_USER');
INSERT INTO public.users(username,password_hash,role) VALUES ('admin', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'ROLE_ADMIN');
INSERT INTO public.users(username,password_hash,role) VALUES ('Geoffrey', '$2a$10$dFqXQmRjK5XBfssMHg6S2u3xYmZStcv3UqQuvEP.iNhJrs5WBXG/2', 'ROLE_USER');
INSERT INTO public.users(username,password_hash,role) VALUES ('Anhthi', '$2a$10$MCFuuI8j95dmfTuCpBOsx.MjO8SY43fbVe9aLW.Z2A50A2TgKBlha', 'ROLE_USER');
INSERT INTO public.users(username,password_hash,role) VALUES ('Emily', '$2a$10$IuEfNGXJozxPeaMc3fbdbO/4acSCAuOEPWxg7LKwhOj2wy572QUHq', 'ROLE_USER');
INSERT INTO public.users(username,password_hash,role) VALUES ('Eric', '$2a$10$f6oz7q409WPF0ZeLG7SIBO8.jeyZJuJBGEc53NU0ORJM/TB8K2JmW', 'ROLE_USER');
INSERT INTO public.users(username,password_hash,role) VALUES ('Ying', '$2a$10$62TkY6hOVHOrOwUko0eTsO1eQ4GrFvPii26N/aQXJeyzcJutvtx/a', 'ROLE_USER');


INSERT INTO public.decks VALUES (48, 'Ethiopian Fried Chicken', 'A history of buttery fried chicken exported from Ethiopia', true, 7);
INSERT INTO public.decks VALUES (2, 'Basic Coding Questions', 'Beginner computer coding questions', true, 3);
INSERT INTO public.decks VALUES (3, 'Roman Empire ', 'History about the great Roman Empire', true, 3);
INSERT INTO public.decks VALUES (4, 'Disney Movies', 'Disney films and culture', true, 3);
INSERT INTO public.decks VALUES (26, 'Python', 'Coding questions to test your knowledge on Python and computers', true, 4);
INSERT INTO public.decks VALUES (5, 'Iconic Characters From TV', 'Best character portrayals from television', true, 3);
INSERT INTO public.decks VALUES (6, 'Paintings from Around the World', 'Famous art pieces around the globe', true, 3);
INSERT INTO public.decks VALUES (7, 'U.S. History', 'General questions about American history', true, 3);
INSERT INTO public.decks VALUES (10, 'Rap Songs', 'Rap music from the past decade', true, 3);
INSERT INTO public.decks VALUES (11, 'Natural Chemistry', 'Questions about the nature of chemistry', true, 4);
INSERT INTO public.decks VALUES (12, 'Greek Gods', 'Famous mythology from Greece', true, 4);
INSERT INTO public.decks VALUES (14, '1980''s American Movies', 'Popular films from America''s Golden Age of Film', true, 4);
INSERT INTO public.decks VALUES (13, 'Sci-Fi Movies', 'Greatest science fiction films ', true, 4);
INSERT INTO public.decks VALUES (15, 'World Geography', 'World geography and borders', true, 4);
INSERT INTO public.decks VALUES (16, 'Baseball', 'Facts about America''s favorite pastime sport', true, 4);
INSERT INTO public.decks VALUES (17, 'Cheetahs', 'The world''s fastest animal', true, 4);
INSERT INTO public.decks VALUES (19, 'Monopoly', 'A best selling board game', true, 4);
INSERT INTO public.decks VALUES (20, 'Richest Actors', 'Most loaded celebrities in Hollywood', true, 4);
INSERT INTO public.decks VALUES (21, 'Sports Cars', 'Fresh and fast. My favorite vehicles.', true, 5);
INSERT INTO public.decks VALUES (22, 'Led Zeppelin', 'Best music from the best rock band', true, 5);
INSERT INTO public.decks VALUES (24, 'Largest Fish', 'Biggest species of oceanic animals', true, 5);
INSERT INTO public.decks VALUES (25, 'World Cup Goals', 'Best goals made in the world''s most played sport', true, 5);
INSERT INTO public.decks VALUES (27, 'Comedies', 'Funniest shows on television', true, 5);
INSERT INTO public.decks VALUES (29, 'Canadian Immigration', 'Canadian Geography and Borders', true, 5);
INSERT INTO public.decks VALUES (30, 'Chess', 'World''s oldest board game', true, 5);
INSERT INTO public.decks VALUES (51, 'Java', 'Coding fundamentals in regards to Java language', true, 4);
INSERT INTO public.decks VALUES (31, 'Running', 'the cheapest sport you can play', true, 6);
INSERT INTO public.decks VALUES (32, 'The American South', 'geographic borders on what makes an American state "southern"', true, 6);
INSERT INTO public.decks VALUES (33, 'Minecraft', 'One of the most played computer games of all time', true, 6);
INSERT INTO public.decks VALUES (34, 'Romantic Comedies', 'Cutest couples on television', true, 6);
INSERT INTO public.decks VALUES (35, 'Rarest Flowers', 'Most difficult to grow flowers in nature', true, 6);
INSERT INTO public.decks VALUES (36, 'Beethoven', 'Best classical music by the famous German composer', true, 6);
INSERT INTO public.decks VALUES (37, 'Building a Car', 'How to build a fully functioning vehicle', true, 6);
INSERT INTO public.decks VALUES (38, 'Exploding Kittens', 'A new and fun board game for all ages!', true, 6);
INSERT INTO public.decks VALUES (40, 'James Bond', 'Learn about all 25 James Bond films', true, 6);
INSERT INTO public.decks VALUES (41, 'iOS', 'Apple''s operating system and how it functions in computers', true, 7);
INSERT INTO public.decks VALUES (42, 'Glee', 'the tv show''s greatest hits and music that inspired it', true, 7);
INSERT INTO public.decks VALUES (43, 'European Sculptures', 'Ancient and contemporary European art pieces', true, 7);
INSERT INTO public.decks VALUES (44, 'Opera Singers', 'Get to know the celebrities of the world of theatre', true, 7);
INSERT INTO public.decks VALUES (45, 'Harry Potter', 'America''s most beloved childhood book series', true, 7);
INSERT INTO public.decks VALUES (46, 'Solar System', 'What nature looks like outside of our planet', true, 7);
INSERT INTO public.decks VALUES (47, 'The Wire', 'Best scenes from one of the greatest television series of all time', true, 7);
INSERT INTO public.decks VALUES (49, 'Jazz', 'Contemporary jazz music ', true, 7);
INSERT INTO public.decks VALUES (50, 'Homo Sapiens', 'How humans evolved from animals', true, 7);
INSERT INTO public.decks VALUES (8, 'Foreign Musicals', 'How other countries put on American musicals', true, 3);
INSERT INTO public.decks VALUES (9, 'Diversity on Broadway', 'The history of race-blind castings in musicals', true, 3);
INSERT INTO public.decks VALUES (18, 'National Parks', 'Historic parks and pre-historic plants still found in nature', true, 7);
INSERT INTO public.decks VALUES (23, 'West African History', 'History of Benin, Cape Verde, Gambia, Ghana, Guinea, Ivory Coast', true, 4);
INSERT INTO public.decks VALUES (52, 'Modern T.V.', 'Drama and soap operas from 2010s television', true, 4);
INSERT INTO public.decks VALUES (1, 'Pop Culture', 'Pop culture about famous contemporary books!', true, 3);
INSERT INTO public.decks VALUES (28, 'Fantasy Novels', 'High fantasy books from medieval times', true, 3);
INSERT INTO public.decks VALUES (39, 'Internet Websites', 'Questions about Google, YouTube and other general sites', true, 3);
INSERT INTO public.decks VALUES (53, 'Popular Trivia', 'Fun questions to test your knowledge about pop culture!', true, 3);


INSERT INTO public.user_deck VALUES (1, 3);
INSERT INTO public.user_deck VALUES (2, 3);
INSERT INTO public.user_deck VALUES (3, 3);
INSERT INTO public.user_deck VALUES (4, 3);
INSERT INTO public.user_deck VALUES (5, 3);
INSERT INTO public.user_deck VALUES (6, 3);
INSERT INTO public.user_deck VALUES (7, 3);
INSERT INTO public.user_deck VALUES (8, 3);
INSERT INTO public.user_deck VALUES (9, 3);
INSERT INTO public.user_deck VALUES (10, 3);
INSERT INTO public.user_deck VALUES (11, 4);
INSERT INTO public.user_deck VALUES (12, 4);
INSERT INTO public.user_deck VALUES (13, 4);
INSERT INTO public.user_deck VALUES (14, 4);
INSERT INTO public.user_deck VALUES (15, 4);
INSERT INTO public.user_deck VALUES (16, 4);
INSERT INTO public.user_deck VALUES (17, 4);
INSERT INTO public.user_deck VALUES (18, 4);
INSERT INTO public.user_deck VALUES (19, 4);
INSERT INTO public.user_deck VALUES (20, 4);
INSERT INTO public.user_deck VALUES (21, 5);
INSERT INTO public.user_deck VALUES (22, 5);
INSERT INTO public.user_deck VALUES (23, 5);
INSERT INTO public.user_deck VALUES (24, 5);
INSERT INTO public.user_deck VALUES (25, 5);
INSERT INTO public.user_deck VALUES (26, 5);
INSERT INTO public.user_deck VALUES (27, 5);
INSERT INTO public.user_deck VALUES (28, 5);
INSERT INTO public.user_deck VALUES (29, 5);
INSERT INTO public.user_deck VALUES (30, 5);
INSERT INTO public.user_deck VALUES (31, 6);
INSERT INTO public.user_deck VALUES (32, 6);
INSERT INTO public.user_deck VALUES (33, 6);
INSERT INTO public.user_deck VALUES (34, 6);
INSERT INTO public.user_deck VALUES (35, 6);
INSERT INTO public.user_deck VALUES (36, 6);
INSERT INTO public.user_deck VALUES (37, 6);
INSERT INTO public.user_deck VALUES (38, 6);
INSERT INTO public.user_deck VALUES (39, 6);
INSERT INTO public.user_deck VALUES (40, 6);
INSERT INTO public.user_deck VALUES (41, 7);
INSERT INTO public.user_deck VALUES (42, 7);
INSERT INTO public.user_deck VALUES (43, 7);
INSERT INTO public.user_deck VALUES (44, 7);
INSERT INTO public.user_deck VALUES (45, 7);
INSERT INTO public.user_deck VALUES (46, 7);
INSERT INTO public.user_deck VALUES (47, 7);
INSERT INTO public.user_deck VALUES (48, 7);
INSERT INTO public.user_deck VALUES (49, 7);
INSERT INTO public.user_deck VALUES (50, 7);
INSERT INTO public.user_deck VALUES (51, 4);
INSERT INTO public.user_deck VALUES (52, 4);
INSERT INTO public.user_deck VALUES (53, 3);


INSERT INTO public.cards VALUES (2, 1, 'Who wrote the novel ''Fear And Loathing In Las Vegas''?', 'Hunter S. Thompson', 3, 1);
INSERT INTO public.cards VALUES (4, 1, 'What''s Harry Potter''s dad''s name?', 'James Potter', 3, 1);
INSERT INTO public.cards VALUES (5, 1, 'Who wrote the young adult novel "The Fault in Our Stars"?', 'John Green', 3, 2);
INSERT INTO public.cards VALUES (6, 1, 'What is the name of the three headed dog in Harry Potter and the Sorcerer''s Stone?', 'Fluffy', 3, 1);
INSERT INTO public.cards VALUES (7, 1, 'What is the title of the first Sherlock Holmes book by Arthur Conan Doyle?', 'A Study in Scarlet', 3, 0);
INSERT INTO public.cards VALUES (8, 1, 'What is the name of Sherlock Holmes''s brother?', 'Mycroft Holmes', 3, 1);
INSERT INTO public.cards VALUES (9, 1, 'What was the first ever entry written for the SCP Foundation collaborative writing project?', 'SCP-173', 3, 2);
INSERT INTO public.cards VALUES (10, 1, 'Who wrote "A Tale of Two Cities"?', 'Charles Dickens', 3, 1);
INSERT INTO public.cards VALUES (11, 2, 'In any programming language, what is the most common way to iterate through an array?', '''For'' loops', 3, 2);
INSERT INTO public.cards VALUES (12, 2, 'According to the International System of Units, how many bytes are in a kilobyte of RAM?', '1000', 3, 1);
INSERT INTO public.cards VALUES (13, 2, 'What does GHz stand for?', 'Gigahertz', 3, 1);
INSERT INTO public.cards VALUES (14, 2, 'If you were to code software in this language you''d only be able to type 0''s and 1''s.', 'Binary', 3, 1);
INSERT INTO public.cards VALUES (15, 2, 'What is the most preferred image format used for logos in the Wikimedia database?', '.svg', 3, 1);
INSERT INTO public.cards VALUES (16, 2, 'How many kilobytes in one gigabyte (in decimal)?', '1000000', 3, 1);
INSERT INTO public.cards VALUES (17, 2, 'The numbering system with a radix of 16 is more commonly referred to as ', 'Hexidecimal', 3, 1);
INSERT INTO public.cards VALUES (18, 2, 'How many values can a single byte represent?', '256', 3, 0);
INSERT INTO public.cards VALUES (19, 2, 'How long is an IPv6 address?', '128 bits', 3, 1);
INSERT INTO public.cards VALUES (20, 2, 'What language does Node.js use?', 'JavaScript', 3, 1);
INSERT INTO public.cards VALUES (22, 3, 'The original Roman alphabet lacked the following letters EXCEPT:', 'X', 3, 2);
INSERT INTO public.cards VALUES (23, 3, 'The collapse of the Soviet Union took place in which year?', '1991', 3, 1);
INSERT INTO public.cards VALUES (24, 3, 'When did the Battle of the Somme begin?', 'July 1st, 1916', 3, 2);
INSERT INTO public.cards VALUES (25, 3, 'What was the first sport to have been played on the moon?', 'Golf', 3, 2);
INSERT INTO public.cards VALUES (26, 3, 'These two countries held a commonwealth from the 16th to 18th century.', 'Poland and Lithuania', 3, 1);
INSERT INTO public.cards VALUES (27, 3, 'What is the historical name of Sri Lanka?', 'Ceylon', 3, 1);
INSERT INTO public.cards VALUES (28, 3, 'What was the name commonly given to the ancient trade routes that connected the East and West of Eurasia?', 'Silk Road', 3, 2);
INSERT INTO public.cards VALUES (29, 3, 'What does the United States of America celebrate during the 4th of July?', 'The signing of the Declaration of Independence', 3, 1);
INSERT INTO public.cards VALUES (30, 3, 'Who was the first American in space?', 'Alan Shephard', 3, 2);
INSERT INTO public.cards VALUES (31, 4, 'Which movie released in 2016 features Superman and Batman fighting?', 'Batman v Superman: Dawn of Justice', 3, 1);
INSERT INTO public.cards VALUES (32, 4, 'Which animated movie was first to feature a celebrity as a voice actor?', 'Aladdin', 3, 2);
INSERT INTO public.cards VALUES (33, 4, 'Who played the female lead in the 1933 film "King Kong"?', 'Fay Wray', 3, 2);
INSERT INTO public.cards VALUES (34, 4, 'What was Dorothy''s surname in ''The Wizard Of Oz''?', 'Gale', 3, 0);
INSERT INTO public.cards VALUES (35, 4, 'What is the oldest Disney film?', 'Snow White and the Seven Dwarfs', 3, 1);
INSERT INTO public.cards VALUES (36, 4, 'When does "Rogue One: A Star Wars Story" take place chronologically in the series?', 'Between Episode 3 and 4', 3, 1);
INSERT INTO public.cards VALUES (37, 4, 'In the 1992 film "Army of Darkness", what name does Ash give to his double-barreled shotgun?', 'Boomstick', 3, 0);
INSERT INTO public.cards VALUES (38, 4, 'Which of these Movies was NOT released in 1996?', 'Gladiator', 3, 1);
INSERT INTO public.cards VALUES (39, 4, 'Who directed the Kill Bill movies?', 'Quentin Tarantino', 3, 1);
INSERT INTO public.cards VALUES (40, 4, 'The 1996 film ''Fargo'' is primarily set in which US state?', 'Minnesota', 3, 1);
INSERT INTO public.cards VALUES (41, 5, 'Which of these Bojack Horseman characters is a human?', 'Todd Chavez', 3, 2);
INSERT INTO public.cards VALUES (42, 5, 'When did the TV show Rick and Morty first air on Adult Swim?', '2013', 3, 2);
INSERT INTO public.cards VALUES (44, 5, 'In the show "Tengen Toppa Gurren Lagann" what is the name of the character who force everyone to live underground?', 'Lordgenome', 3, 1);
INSERT INTO public.cards VALUES (45, 5, 'What is the real name of the famous spanish humorist, El Risitas?', 'Juan Joya Borga', 3, 2);
INSERT INTO public.cards VALUES (46, 5, 'In season one of the Netflix political drama "House of Cards", what government position does Frank Underwood hold?', 'House Majority Whip', 3, 0);
INSERT INTO public.cards VALUES (47, 5, 'What NBC sitcom once saw two of its characters try to pitch NBC on a sitcom about nothing?', 'Seinfeld', 3, 1);
INSERT INTO public.cards VALUES (48, 5, 'What was the name of the teenage witch played by Melisa Joan Hart who lives with her witch aunts Hilda and Zelda?', 'Sabrina', 3, 0);
INSERT INTO public.cards VALUES (49, 5, 'What TV show is about a grandfather dragging his grandson around on adventures?', 'Rick & Morty', 3, 1);
INSERT INTO public.cards VALUES (50, 5, 'In the show "Futurama" what is Fry''s full name?', 'Philip J. Fry', 3, 0);
INSERT INTO public.cards VALUES (51, 6, 'What is the capital of the American state of Arizona?', 'Phoenix', 3, 1);
INSERT INTO public.cards VALUES (52, 6, 'Which country does Austria not border?', 'France', 3, 1);
INSERT INTO public.cards VALUES (53, 6, 'Which US state has the highest population?', 'California', 3, 0);
INSERT INTO public.cards VALUES (54, 6, 'How many time zones does China have?', '1', 3, 0);
INSERT INTO public.cards VALUES (55, 6, 'What country has a horizontal bicolor red and white flag?', 'Monaco', 3, 1);
INSERT INTO public.cards VALUES (56, 6, 'Which of the following Japanese islands is the biggest?', 'Honshu', 3, 2);
INSERT INTO public.cards VALUES (57, 6, 'What is the smallest country in the world?', 'Vatican City', 3, 1);
INSERT INTO public.cards VALUES (58, 6, 'The Alps are a mountain range on which continent?', 'Europe', 3, 1);
INSERT INTO public.cards VALUES (59, 6, 'The longest shared border in the world can be found between which two nations?', 'Canada and the United States', 3, 1);
INSERT INTO public.cards VALUES (60, 6, 'What is the largest country in the world ?', 'Russian Federation', 3, 0);
INSERT INTO public.cards VALUES (61, 7, 'What is the shape of the toy invented by Hungarian professor Ernő Rubik?', 'Cube', 3, 1);
INSERT INTO public.cards VALUES (62, 7, 'What is the nickname of the US state of California?', 'Golden State', 3, 1);
INSERT INTO public.cards VALUES (63, 7, 'Who is depicted on the US hundred dollar bill?', 'Benjamin Franklin', 3, 1);
INSERT INTO public.cards VALUES (65, 7, 'Which of the following presidents is not on Mount Rushmore?', 'John F. Kennedy', 3, 0);
INSERT INTO public.cards VALUES (66, 7, 'Which of the following is the IATA code for Manchester Airport?', 'MAN', 3, 2);
INSERT INTO public.cards VALUES (67, 7, 'What zodiac sign is represented by a pair of scales?', 'Libra', 3, 1);
INSERT INTO public.cards VALUES (68, 7, 'When one is "envious", they are said to be what color?', 'Green', 3, 0);
INSERT INTO public.cards VALUES (69, 7, 'What is the French word for "fish"?', 'poisson', 3, 1);
INSERT INTO public.cards VALUES (71, 10, 'Which rap group released the album "Straight Outta Compton"?', 'N.W.A', 3, NULL);
INSERT INTO public.cards VALUES (72, 10, 'The Red Hot Chili Pepper song "Give It Away" is from what album?', 'Blood Sugar Sex Magik', 3, NULL);
INSERT INTO public.cards VALUES (73, 10, 'Where does the Mac part of the name Fleetwood Mac come from?', 'John McVie', 3, NULL);
INSERT INTO public.cards VALUES (74, 10, 'What was the subject of the 2014 song "CoCo" by American rapper O. T. Genasis?', 'Cocaine', 3, NULL);
INSERT INTO public.cards VALUES (75, 10, 'Which song on Daft Punk''s "Random Access Memories" features Pharrell Williams?', 'Get Lucky', 3, NULL);
INSERT INTO public.cards VALUES (76, 10, 'Which of the following songs did Elton John perform following Princess Diane''s passing?', 'Candles in the Wind', 3, NULL);
INSERT INTO public.cards VALUES (77, 10, 'Which group performs the song "Crash into Me"?', 'Dave Matthews Band', 3, NULL);
INSERT INTO public.cards VALUES (78, 10, 'Which punk rock band released hit songs such as "Californication", "Can''t Stop" and "Under the Bridge"?', 'Red Hot Chilli Peppers', 3, NULL);
INSERT INTO public.cards VALUES (79, 10, 'Which music publication is often abbreviated to NME?', 'New Musical Express', 3, NULL);
INSERT INTO public.cards VALUES (80, 10, 'What is the name of Rivers Cuomo''s wife?', 'Kyoko Ito', 3, NULL);
INSERT INTO public.cards VALUES (82, 11, 'Which element has the chemical symbol ''Fe''?', 'Iron', 4, 2);
INSERT INTO public.cards VALUES (83, 11, 'Which is the longest bone in the human body? ', 'Femur', 4, 2);
INSERT INTO public.cards VALUES (84, 11, 'What is the first element on the periodic table?', 'Hydrogen', 4, 2);
INSERT INTO public.cards VALUES (85, 11, 'What is the standard SI unit for temperature?', 'Kelvin', 4, 2);
INSERT INTO public.cards VALUES (86, 11, 'Who is the chemical element Curium named after?', 'Marie & Pierre Curie', 4, 2);
INSERT INTO public.cards VALUES (87, 11, 'The human heart has how many chambers?', '4', 4, 2);
INSERT INTO public.cards VALUES (89, 11, 'How many chromosomes are in your body cells?', '23', 4, 2);
INSERT INTO public.cards VALUES (90, 11, 'What animal takes part in Schrödinger''s most famous thought experiment?', 'Cat', 4, 2);
INSERT INTO public.cards VALUES (91, 12, 'Who was the only god from Greece who did not get a name change in Rome?', 'Apollo', 4, 1);
INSERT INTO public.cards VALUES (92, 12, 'The ancient Roman god of war was commonly known as which of the following?', 'Mars', 4, 1);
INSERT INTO public.cards VALUES (93, 12, 'Who in Greek mythology, who led the Argonauts in search of the Golden Fleece?', 'Jason', 4, 0);
INSERT INTO public.cards VALUES (94, 12, 'Who was the King of Gods in Ancient Greek mythology?', 'Zeus', 4, 2);
INSERT INTO public.cards VALUES (95, 12, 'Which Greek & Roman god was known as the god of music, truth and prophecy, healing, the sun and light, plague, poetry, and more?', 'Apollo', 4, 0);
INSERT INTO public.cards VALUES (96, 12, 'The greek god Poseidon was the god of what?', 'The Sea', 4, 2);
INSERT INTO public.cards VALUES (97, 12, 'In Greek mythology, who is the god of wine?', 'Dionysus', 4, 1);
INSERT INTO public.cards VALUES (98, 12, 'Which of these mythological creatures is said to be half-man and half-horse?', 'Centaur', 4, 1);
INSERT INTO public.cards VALUES (99, 12, 'What mytological creatures have women''s faces and vultures'' bodies?', 'Harpies', 4, 1);
INSERT INTO public.cards VALUES (100, 12, 'The Nike apparel and footwear brand takes it''s name from the Greek goddess of what?', 'Victory', 4, 0);
INSERT INTO public.cards VALUES (111, 14, 'What breed of dog was Marley in the film "Marley & Me" (2008)?', 'Labrador Retriever', 4, 1);
INSERT INTO public.cards VALUES (112, 14, 'Who played the female lead in the 1933 film "King Kong"?', 'Fay Wray', 4, 0);
INSERT INTO public.cards VALUES (113, 14, 'Which movie contains the quote, "Say hello to my little friend!"?', 'Scarface', 4, 2);
INSERT INTO public.cards VALUES (114, 14, 'This movie contains the quote, "I feel the need ... the need for speed!"', 'Top Gun', 4, 1);
INSERT INTO public.cards VALUES (115, 14, 'Which of these movies did Jeff Bridges not star in?', 'The Hateful Eight', 4, 1);
INSERT INTO public.cards VALUES (116, 14, 'Which actor plays Obi-Wan Kenobi in Star Wars Episodes I-lll?', 'Ewan McGregor', 4, 1);
INSERT INTO public.cards VALUES (117, 14, 'In the 1992 film "Army of Darkness", what name does Ash give to his double-barreled shotgun?', 'Boomstick', 4, 0);
INSERT INTO public.cards VALUES (118, 14, 'Which of the following actors has only been in a Quentin Tarantino directed film once?', 'John Travolta', 4, 2);
INSERT INTO public.cards VALUES (119, 14, 'The 1996 film ''Fargo'' is primarily set in which US state?', 'Minnesota', 4, 1);
INSERT INTO public.cards VALUES (120, 14, 'Which of these films is NOT set in Los Angeles?', 'RoboCop', 4, 1);
INSERT INTO public.cards VALUES (102, 13, 'Which of the following was not one of "The Magnificent Seven"?', 'Clint Eastwood', 4, 1);
INSERT INTO public.cards VALUES (103, 13, 'The Queen song `A Kind Of Magic` is featured in which 1986 film?', 'Highlander', 4, 1);
INSERT INTO public.cards VALUES (104, 13, 'What is the oldest Disney film?', 'Snow White and the Seven Dwarfs', 4, 2);
INSERT INTO public.cards VALUES (105, 13, 'Who in Pulp Fiction says "No, they got the metric system there, they wouldn''t know what the fuck a Quarter Pounder is."', 'Vincent Vega', 4, 0);
INSERT INTO public.cards VALUES (106, 13, 'Which actor plays Obi-Wan Kenobi in Star Wars Episodes I-lll?', 'Ewan McGregor', 4, 1);
INSERT INTO public.cards VALUES (107, 13, 'What is the name of the island that "Jurassic Park" is built on?', 'Isla Nublar', 4, 0);
INSERT INTO public.cards VALUES (108, 13, 'For the film "Raiders of The Lost Ark", what was Harrison Ford sick with during the filming of the Cairo chase?', 'Dysentery', 4, 2);
INSERT INTO public.cards VALUES (109, 13, 'Which of these Movies was NOT released in 1996?', 'Gladiator', 4, 1);
INSERT INTO public.cards VALUES (110, 13, 'The 1996 film ''Fargo'' is primarily set in which US state?', 'Minnesota', 4, 2);
INSERT INTO public.cards VALUES (121, 15, 'What state is the largest state of the United States of America?', 'Alaska', 4, 2);
INSERT INTO public.cards VALUES (122, 15, 'Which country does Austria not border?', 'France', 4, 1);
INSERT INTO public.cards VALUES (123, 15, 'Which of the following European languages is classified as a "language isolate?"', 'Basque', 4, 2);
INSERT INTO public.cards VALUES (124, 15, 'Which Russian oblast forms a border with Poland?', 'Kaliningrad', 4, 1);
INSERT INTO public.cards VALUES (125, 15, 'What is the Capital of the United States?', 'Washington, D.C.', 4, 0);
INSERT INTO public.cards VALUES (126, 15, 'What is the capital of the US State of New York?', 'Albany', 4, 2);
INSERT INTO public.cards VALUES (127, 15, 'How many stars are featured on New Zealand''s flag?', '4', 4, 1);
INSERT INTO public.cards VALUES (128, 15, 'What is the smallest country in the world?', 'Vatican City', 4, 2);
INSERT INTO public.cards VALUES (129, 15, 'Which ocean borders the west coast of the United States?', 'Pacific', 4, 1);
INSERT INTO public.cards VALUES (130, 15, 'What is Laos?', 'Country', 4, 0);
INSERT INTO public.cards VALUES (131, 16, 'In golf, what name is given to a hole score of two under par?', 'Eagle', 4, 2);
INSERT INTO public.cards VALUES (133, 16, 'Which country will host the 2020 Summer Olympics?', 'Japan', 4, 0);
INSERT INTO public.cards VALUES (134, 16, 'Who won the 2015 Formula 1 World Championship?', 'Lewis Hamilton', 4, 2);
INSERT INTO public.cards VALUES (135, 16, 'What is the most common type of pitch thrown by pitchers in baseball?', 'Fastball', 4, 1);
INSERT INTO public.cards VALUES (136, 16, 'Who is often called "the Maestro" in the men''s tennis circuit?', 'Roger Federer', 4, 1);
INSERT INTO public.cards VALUES (137, 16, 'Which African American is in part responsible for integrating  Major League baseball?', 'Jackie Robinson', 4, 1);
INSERT INTO public.cards VALUES (138, 16, 'When was the FC Schalke 04 founded?', '1904', 4, 1);
INSERT INTO public.cards VALUES (139, 16, 'Who won the UEFA Champions League in 2017?', 'Real Madrid C.F.', 4, 0);
INSERT INTO public.cards VALUES (151, 18, 'Which Apollo mission was the first one to land on the Moon?', 'Apollo 11', 4, NULL);
INSERT INTO public.cards VALUES (152, 18, 'What does the letter ''S'' stand for in ''NASA''?', 'Space', 4, NULL);
INSERT INTO public.cards VALUES (153, 18, 'This element, when overcome with extreme heat and pressure, creates diamonds.', 'Carbon', 4, NULL);
INSERT INTO public.cards VALUES (154, 18, 'What is the hottest planet in the Solar System?', 'Venus', 4, NULL);
INSERT INTO public.cards VALUES (155, 18, 'How many planets make up our Solar System?', '8', 4, NULL);
INSERT INTO public.cards VALUES (156, 18, 'What is the chemical makeup of water?', 'H20', 4, NULL);
INSERT INTO public.cards VALUES (157, 18, 'Which is the most abundant element in the universe?', 'Hydrogen', 4, NULL);
INSERT INTO public.cards VALUES (158, 18, 'The medical term for the belly button is which of the following?', 'Umbilicus', 4, NULL);
INSERT INTO public.cards VALUES (159, 18, 'Which element has the highest melting point?', 'Carbon', 4, NULL);
INSERT INTO public.cards VALUES (160, 18, 'Who discovered the Law of Gravity?', 'Sir Isaac Newton', 4, NULL);
INSERT INTO public.cards VALUES (140, 16, 'In the 2014 FIFA World Cup, what was the final score in the match Brazil - Germany?', '1-7', 4, 2);
INSERT INTO public.cards VALUES (161, 19, 'How many spaces are there on a standard Monopoly board?', '40', 4, NULL);
INSERT INTO public.cards VALUES (162, 19, 'How many dice are used in the game of Yahtzee?', 'Five', 4, NULL);
INSERT INTO public.cards VALUES (163, 19, 'How many pieces are there on the board at the start of a game of chess?', '32', 4, NULL);
INSERT INTO public.cards VALUES (164, 19, 'How many dots are on a single die?', '21', 4, NULL);
INSERT INTO public.cards VALUES (165, 19, 'Which of these games includes the phrase "Do not pass Go, do not collect $200"?', 'Monopoly', 4, NULL);
INSERT INTO public.cards VALUES (166, 19, 'Which one of these is not a real game in the Dungeons & Dragons series?', 'Extreme Dungeons & Dragons', 4, NULL);
INSERT INTO public.cards VALUES (167, 19, 'The board game Monopoly takes its street names from which real American city?', 'Atlantic City, New Jersey', 4, NULL);
INSERT INTO public.cards VALUES (168, 19, 'When was the board game Twister, released to the public?', 'April 1966', 4, NULL);
INSERT INTO public.cards VALUES (169, 19, 'In board games, an additional or ammended rule that applies to a certain group or place is informally known as a "what" rule?', 'House', 4, NULL);
INSERT INTO public.cards VALUES (170, 19, 'What is the maximum level you can have in a single class in Dungeons and Dragons (5e)?', '20', 4, NULL);
INSERT INTO public.cards VALUES (142, 17, 'What is the scientific name for modern day humans?', 'Homo Sapiens', 4, 1);
INSERT INTO public.cards VALUES (143, 17, 'Hippocampus is the Latin name for which marine creature?', 'Seahorse', 4, 0);
INSERT INTO public.cards VALUES (144, 17, 'How many legs do butterflies have?', '6', 4, 2);
INSERT INTO public.cards VALUES (145, 17, 'What do you call a baby bat?', 'Pup', 4, 1);
INSERT INTO public.cards VALUES (146, 17, 'Which class of animals are newts members of?', 'Amphibian', 4, 0);
INSERT INTO public.cards VALUES (147, 17, 'What is the collective noun for a group of crows?', 'Murder', 4, 1);
INSERT INTO public.cards VALUES (148, 17, 'What colour is the female blackbird?', 'Brown', 4, 2);
INSERT INTO public.cards VALUES (149, 17, 'How many teeth does an adult rabbit have?', '28', 4, 1);
INSERT INTO public.cards VALUES (150, 17, 'What is the name of a rabbit''s abode?', 'Burrow', 4, 0);
INSERT INTO public.cards VALUES (182, 21, 'Which of the following car manufacturers had a war named after it?', 'Toyota', 5, 2);
INSERT INTO public.cards VALUES (183, 21, 'Which of these companies does NOT manufacture motorcycles?', 'Toyota', 5, 1);
INSERT INTO public.cards VALUES (184, 21, 'Automobiles produced by Telsa Motors operate on which form of energy?', 'Electricity', 5, 1);
INSERT INTO public.cards VALUES (186, 21, 'Which car tire manufacturer is famous for its "P Zero" line?', 'Pirelli', 5, 2);
INSERT INTO public.cards VALUES (187, 21, 'The LS7 engine is how many cubic inches?', '427', 5, 1);
INSERT INTO public.cards VALUES (188, 21, 'The LS3 engine is how many cubic inches?', '376', 5, 1);
INSERT INTO public.cards VALUES (189, 21, 'What is the name of Nissan''s most popular electric car?', 'Leaf', 5, 2);
INSERT INTO public.cards VALUES (190, 21, 'What is the fastest road legal car in the world?', 'Koenigsegg Agera RS', 5, 2);
INSERT INTO public.cards VALUES (191, 22, 'Who is the frontman of the band 30 Seconds to Mars?', 'Jared Leto', 5, 1);
INSERT INTO public.cards VALUES (192, 22, 'The Red Hot Chili Pepper song "Give It Away" is from what album?', 'Blood Sugar Sex Magik', 5, 2);
INSERT INTO public.cards VALUES (193, 22, 'Who is the lead singer of the band Coldplay?', 'Chris Martin', 5, 2);
INSERT INTO public.cards VALUES (194, 22, 'Who is the lead singer of the British pop rock band Coldplay?', 'Chris Martin', 5, 1);
INSERT INTO public.cards VALUES (195, 22, 'Sting, the lead vocalist of The Police, primarily plays what instrument?', 'Bass Guitar', 5, 2);
INSERT INTO public.cards VALUES (196, 22, 'According to a song by Belinda Carlisle, Heaven is a place on what?', 'Earth', 5, 1);
INSERT INTO public.cards VALUES (197, 22, 'What was Daft Punk''s first studio album?', 'Homework', 5, 2);
INSERT INTO public.cards VALUES (198, 22, 'Which classical composer wrote the "Moonlight Sonata"?', 'Ludvig Van Beethoven', 5, 1);
INSERT INTO public.cards VALUES (199, 22, 'Which band recorded the album "Parallel Lines"?', 'Blondie', 5, 0);
INSERT INTO public.cards VALUES (200, 22, 'What is the name of Rivers Cuomo''s wife?', 'Kyoko Ito', 5, 1);
INSERT INTO public.cards VALUES (201, 23, 'Which of the following African countries was most successful in resisting colonization?', 'Ethiopia', 5, 2);
INSERT INTO public.cards VALUES (202, 23, 'Which famous world leader is famed for the saying, "Let them eat cake", yet is rumored that he/she never said it at all?', 'Marie Antoinette', 5, 1);
INSERT INTO public.cards VALUES (203, 23, 'The collapse of the Soviet Union took place in which year?', '1991', 5, 0);
INSERT INTO public.cards VALUES (204, 23, 'In which year did the Invasion of Kuwait by Iraq occur?', '1990', 5, 1);
INSERT INTO public.cards VALUES (205, 23, 'When did the Battle of the Somme begin?', 'July 1st, 1916', 5, 0);
INSERT INTO public.cards VALUES (206, 23, 'What was the first sport to have been played on the moon?', 'Golf', 5, 2);
INSERT INTO public.cards VALUES (207, 23, 'These two countries held a commonwealth from the 16th to 18th century.', 'Poland and Lithuania', 5, 1);
INSERT INTO public.cards VALUES (208, 23, 'In 1453, which important city fell?', 'Constantinople', 5, 1);
INSERT INTO public.cards VALUES (209, 23, 'On what street did the 1666 Great Fire of London start?', 'Pudding Lane', 5, 2);
INSERT INTO public.cards VALUES (210, 23, 'In what year was the M1911 pistol designed?', '1911', 5, 2);
INSERT INTO public.cards VALUES (212, 24, 'What is the scientific name for modern day humans?', 'Homo Sapiens', 5, 2);
INSERT INTO public.cards VALUES (214, 24, 'How many legs do butterflies have?', '6', 5, 1);
INSERT INTO public.cards VALUES (215, 24, 'What is Grumpy Cat''s real name?', 'Tardar Sauce', 5, 1);
INSERT INTO public.cards VALUES (216, 24, 'Which class of animals are newts members of?', 'Amphibian', 5, 2);
INSERT INTO public.cards VALUES (217, 24, 'By definition, where does an abyssopelagic animal live?', 'At the bottom of the ocean', 5, 2);
INSERT INTO public.cards VALUES (218, 24, 'What colour is the female blackbird?', 'Brown', 5, 2);
INSERT INTO public.cards VALUES (219, 24, 'How many teeth does an adult rabbit have?', '28', 5, 2);
INSERT INTO public.cards VALUES (220, 24, 'What is the name of a rabbit''s abode?', 'Burrow', 5, 0);
INSERT INTO public.cards VALUES (221, 25, 'Which English football club has the nickname ''The Foxes''?', 'Leicester City', 5, 1);
INSERT INTO public.cards VALUES (222, 25, 'Which country has hosted the 2018 FIFA World Cup?', 'Russia', 5, 1);
INSERT INTO public.cards VALUES (223, 25, 'What was the final score of the Germany vs. Brazil 2014 FIFA World Cup match?', '7 - 1', 5, 2);
INSERT INTO public.cards VALUES (224, 25, 'Which team won 2014 FIFA World Cup in Brazil?', 'Germany', 5, 0);
INSERT INTO public.cards VALUES (211, 24, 'What is the fastest  land animal?', 'Cheetah', 5, 2);
INSERT INTO public.cards VALUES (172, 20, 'Which actress married Michael Douglas in 2000?', 'Catherine Zeta-Jones', 4, 2);
INSERT INTO public.cards VALUES (173, 20, 'What does film maker Dan Bell typically focus his films on?', 'Abandoned Buildings and Dead Malls', 4, 2);
INSERT INTO public.cards VALUES (174, 20, 'What was the cause of Marilyn Monroes suicide?', 'Drug Overdose', 4, 2);
INSERT INTO public.cards VALUES (175, 20, 'Gwyneth Paltrow has a daughter named...?', 'Apple', 4, 2);
INSERT INTO public.cards VALUES (176, 20, 'Which celebrity announced his presidency in 2015?', 'Kanye West', 4, 2);
INSERT INTO public.cards VALUES (177, 20, 'Aubrey Graham is better known as', 'Drake', 4, 2);
INSERT INTO public.cards VALUES (178, 20, 'Neil Hamburger is played by which comedian?', 'Gregg Turkington', 4, 2);
INSERT INTO public.cards VALUES (179, 20, 'By which name is Ramon Estevez better known as?', 'Martin Sheen', 4, 2);
INSERT INTO public.cards VALUES (180, 20, 'What was James Coburn''s last film role before his death?', 'American Gun', 4, 2);
INSERT INTO public.cards VALUES (251, 28, 'Which of the following is the world''s best-selling book?', 'The Lord of the Rings', 5, NULL);
INSERT INTO public.cards VALUES (252, 28, 'Who wrote the novel ''Fear And Loathing In Las Vegas''?', 'Hunter S. Thompson', 5, NULL);
INSERT INTO public.cards VALUES (253, 28, 'How many Harry Potter books are there?', '7', 5, NULL);
INSERT INTO public.cards VALUES (254, 28, 'Who was the author of the 1954 novel, "Lord of the Flies"?', 'William Golding', 5, NULL);
INSERT INTO public.cards VALUES (255, 28, 'What''s the second book in George R. R. Martin''s ''A Song of Ice and Fire'' series?', 'A Clash of Kings', 5, NULL);
INSERT INTO public.cards VALUES (256, 28, 'What was the first ever entry written for the SCP Foundation collaborative writing project?', 'SCP-173', 5, NULL);
INSERT INTO public.cards VALUES (257, 28, 'Which is NOT a book in the Harry Potter Series?', 'The House Elf', 5, NULL);
INSERT INTO public.cards VALUES (258, 28, 'In the novel 1984, written by George Orwell, what is the name of the totalitarian regime that controls Oceania?', 'INGSOC', 5, NULL);
INSERT INTO public.cards VALUES (259, 28, 'Who wrote "A Tale of Two Cities"?', 'Charles Dickens', 5, NULL);
INSERT INTO public.cards VALUES (260, 28, 'What was Sir Handel''s original name in "The Railway Series" and it''s animated counterpart "Thomas and Friends?"', 'Falcon', 5, NULL);
INSERT INTO public.cards VALUES (250, 27, 'In Two and a Half Men, what is Alan Harper''s son''s name?', 'Jake', 5, 2);
INSERT INTO public.cards VALUES (225, 25, 'In Baseball, how many times does the ball have to be pitched outside of the strike zone before the batter is walked?', '4', 5, 1);
INSERT INTO public.cards VALUES (226, 25, 'What year did the New Orleans Saints win the Super Bowl?', '2010', 5, 2);
INSERT INTO public.cards VALUES (227, 25, 'What team did England beat to win in the 1966 World Cup final?', 'West Germany', 5, 1);
INSERT INTO public.cards VALUES (228, 25, 'Who is often called "the Maestro" in the men''s tennis circuit?', 'Roger Federer', 5, 1);
INSERT INTO public.cards VALUES (229, 25, 'Which African American is in part responsible for integrating  Major League baseball?', 'Jackie Robinson', 5, 2);
INSERT INTO public.cards VALUES (230, 25, 'Which player holds the NHL record of 2,857 points?', 'Wayne Gretzky', 5, 1);
INSERT INTO public.cards VALUES (262, 29, 'Which country does Austria not border?', 'France', 5, 1);
INSERT INTO public.cards VALUES (263, 29, 'How many federal states does Germany have?', '16', 5, 1);
INSERT INTO public.cards VALUES (264, 29, 'The derisive acronym "PIIGS" refers to which of the following European countries and their economic statuses?', 'Portugal, Ireland, Italy, Greece, Spain', 5, 0);
INSERT INTO public.cards VALUES (265, 29, 'What name was historically used for the Turkish city currently known as Istanbul?', 'Constantinople', 5, 1);
INSERT INTO public.cards VALUES (266, 29, 'Which UK country features a dragon on their flag?', 'Wales', 5, 1);
INSERT INTO public.cards VALUES (267, 29, 'Which country is the home of the largest Japanese population outside of Japan?', 'Brazil', 5, 0);
INSERT INTO public.cards VALUES (268, 29, 'What is the capital of Scotland?', 'Edinburgh', 5, 2);
INSERT INTO public.cards VALUES (269, 29, 'Which small country is located between the borders of France and Spain?', 'Andorra', 5, 1);
INSERT INTO public.cards VALUES (270, 29, 'Greenland is a part of which kingdom?', 'Denmark', 5, 2);
INSERT INTO public.cards VALUES (261, 29, 'What country is the second largest in the world by area?', 'Canada', 5, 1);
INSERT INTO public.cards VALUES (241, 27, 'In the TV show "Cheers", Sam Malone was a former relief pitcher for which baseball team?', 'Boston Red Sox', 5, 2);
INSERT INTO public.cards VALUES (242, 27, 'Which of these Bojack Horseman characters is a human?', 'Todd Chavez', 5, 2);
INSERT INTO public.cards VALUES (243, 27, 'In the show, Doctor Who, what does T.A.R.D.I.S stand for?', 'Time And Relative Dimensions In Space', 5, 2);
INSERT INTO public.cards VALUES (244, 27, 'The "Psycho" series of videos on YouTube was created by which of the following?', 'RiDGiD STUDiOS', 5, 2);
INSERT INTO public.cards VALUES (245, 27, 'How many seasons did "Stargate SG-1" have?', '10', 5, 2);
INSERT INTO public.cards VALUES (246, 27, 'In the show "Tengen Toppa Gurren Lagann" what is the name of the character who force everyone to live underground?', 'Lordgenome', 5, 2);
INSERT INTO public.cards VALUES (247, 27, 'How many seasons did the Sci-Fi television show "Stargate Universe" have?', '2', 5, 2);
INSERT INTO public.cards VALUES (248, 27, 'What is the name of Chris''s brother in "Everybody Hates Chris"?', 'Drew', 5, 2);
INSERT INTO public.cards VALUES (249, 27, 'In the cartoon ''SpongeBob SquarePants'', what did the acronym E.V.I.L stand for?', 'Every Villain Is Lemons', 5, 2);
INSERT INTO public.cards VALUES (271, 30, 'Carcassonne is based on which French town?', 'Carcassonne', 5, 0);
INSERT INTO public.cards VALUES (272, 30, 'How many pieces are there on the board at the start of a game of chess?', '32', 5, 0);
INSERT INTO public.cards VALUES (273, 30, 'On a standard Monopoly board, which square is diagonally opposite ''Go''? ', 'Free Parking', 5, 0);
INSERT INTO public.cards VALUES (274, 30, 'How many dots are on a single die?', '21', 5, 0);
INSERT INTO public.cards VALUES (275, 30, 'Which of these games includes the phrase "Do not pass Go, do not collect $200"?', 'Monopoly', 5, 0);
INSERT INTO public.cards VALUES (276, 30, 'Which one of these is not a real game in the Dungeons & Dragons series?', 'Extreme Dungeons & Dragons', 5, 0);
INSERT INTO public.cards VALUES (277, 30, 'The board game Monopoly takes its street names from which real American city?', 'Atlantic City, New Jersey', 5, 0);
INSERT INTO public.cards VALUES (278, 30, 'When was the board game Twister, released to the public?', 'April 1966', 5, 0);
INSERT INTO public.cards VALUES (279, 30, 'In board games, an additional or ammended rule that applies to a certain group or place is informally known as a "what" rule?', 'House', 5, 0);
INSERT INTO public.cards VALUES (280, 30, 'What is the maximum level you can have in a single class in Dungeons and Dragons (5e)?', '20', 5, 0);
INSERT INTO public.cards VALUES (291, 32, 'Which of these is NOT an Australian state or territory?', 'Alberta', 6, 1);
INSERT INTO public.cards VALUES (232, 26, 'What does CPU stand for?', 'Central Processing Unit', 5, 1);
INSERT INTO public.cards VALUES (233, 26, 'What does GHz stand for?', 'Gigahertz', 5, 0);
INSERT INTO public.cards VALUES (234, 26, 'HTML is what type of language?', 'Markup Language', 5, 1);
INSERT INTO public.cards VALUES (235, 26, 'What does the Prt Sc button do?', 'Captures what''s on the screen and copies it to your clipboard', 5, 2);
INSERT INTO public.cards VALUES (236, 26, 'In "Hexadecimal", what color would be displayed from the color code? "#00FF00"?', 'Green', 5, 1);
INSERT INTO public.cards VALUES (237, 26, 'Which computer language would you associate Django framework with?', 'Python', 5, 1);
INSERT INTO public.cards VALUES (238, 26, 'The numbering system with a radix of 16 is more commonly referred to as ', 'Hexidecimal', 5, 0);
INSERT INTO public.cards VALUES (239, 26, 'Which programming language shares its name with an island in Indonesia?', 'Java', 5, 2);
INSERT INTO public.cards VALUES (240, 26, 'What does the computer software acronym JVM stand for?', 'Java Virtual Machine', 5, 1);
INSERT INTO public.cards VALUES (282, 31, 'Which English football club has the nickname ''The Foxes''?', 'Leicester City', 6, 2);
INSERT INTO public.cards VALUES (283, 31, 'How many soccer players should be on the field at the same time?', '22', 6, 1);
INSERT INTO public.cards VALUES (284, 31, 'Which driver has been the Formula 1 world champion for a record 7 times?', 'Michael Schumacher', 6, 1);
INSERT INTO public.cards VALUES (286, 31, 'What team won the 2016 MLS Cup?', 'Seattle Sounders', 6, 0);
INSERT INTO public.cards VALUES (287, 31, 'When was the first official international game played?', '1872', 6, 2);
INSERT INTO public.cards VALUES (288, 31, 'What is the most common type of pitch thrown by pitchers in baseball?', 'Fastball', 6, 1);
INSERT INTO public.cards VALUES (289, 31, 'In bowling, what is the term used for getting three consecutive strikes?', 'Turkey', 6, 2);
INSERT INTO public.cards VALUES (290, 31, 'Who won the UEFA Champions League in 2017?', 'Real Madrid C.F.', 6, 1);
INSERT INTO public.cards VALUES (281, 31, 'Which of the following sports is not part of the triathlon?', 'Horse-Riding', 6, 2);
INSERT INTO public.cards VALUES (292, 32, 'Which Russian oblast forms a border with Poland?', 'Kaliningrad', 6, 2);
INSERT INTO public.cards VALUES (293, 32, 'What is the 15th letter of the Greek alphabet?', 'Omicron (Ο)', 6, 2);
INSERT INTO public.cards VALUES (294, 32, 'What name was historically used for the Turkish city currently known as Istanbul?', 'Constantinople', 6, 1);
INSERT INTO public.cards VALUES (295, 32, 'What is the nickname for the US state Delaware?', 'The First State', 6, 1);
INSERT INTO public.cards VALUES (296, 32, 'What is the capital of the US State of New York?', 'Albany', 6, 0);
INSERT INTO public.cards VALUES (297, 32, 'What is the capital of Spain?', 'Madrid', 6, 0);
INSERT INTO public.cards VALUES (298, 32, 'What is the largest country in the world?', 'Russia', 6, 1);
INSERT INTO public.cards VALUES (299, 32, 'Where would you find the "Spanish Steps"?', 'Rome, Italy', 6, 2);
INSERT INTO public.cards VALUES (300, 32, 'What is Laos?', 'Country', 6, 1);
INSERT INTO public.cards VALUES (301, 33, 'What does the "MP" stand for in MP3?', 'Moving Picture', 6, 1);
INSERT INTO public.cards VALUES (302, 33, 'According to the International System of Units, how many bytes are in a kilobyte of RAM?', '1000', 6, 0);
INSERT INTO public.cards VALUES (303, 33, 'When Gmail first launched, how much storage did it provide for your email?', '1GB', 6, 0);
INSERT INTO public.cards VALUES (304, 33, 'What does GHz stand for?', 'Gigahertz', 6, 1);
INSERT INTO public.cards VALUES (305, 33, 'If you were to code software in this language you''d only be able to type 0''s and 1''s.', 'Binary', 6, 2);
INSERT INTO public.cards VALUES (307, 33, 'In "Hexadecimal", what color would be displayed from the color code? "#00FF00"?', 'Green', 6, 0);
INSERT INTO public.cards VALUES (308, 33, 'The numbering system with a radix of 16 is more commonly referred to as ', 'Hexidecimal', 6, 0);
INSERT INTO public.cards VALUES (309, 33, 'This mobile OS held the largest market share in 2012.', 'iOS', 6, 0);
INSERT INTO public.cards VALUES (310, 33, 'What language does Node.js use?', 'JavaScript', 6, 0);
INSERT INTO public.cards VALUES (311, 34, 'In the TV show "Cheers", Sam Malone was a former relief pitcher for which baseball team?', 'Boston Red Sox', 6, 2);
INSERT INTO public.cards VALUES (312, 34, 'In Supernatural, what''s is Sam''s brothers name?', 'Dean', 6, 1);
INSERT INTO public.cards VALUES (313, 34, 'In DuckTales, what is the name of the city where all the main characters live?', 'Duckburg', 6, 1);
INSERT INTO public.cards VALUES (314, 34, 'Which show is known for the songs "You are a Pirate", "Cooking by the Book" and "We Are Number One"?', 'LazyTown', 6, 0);
INSERT INTO public.cards VALUES (315, 34, 'In "Star Trek: Voyager", which episode did Voyager establish real-time communication with Starfleet Headquarters?', 'Pathfinder', 6, 1);
INSERT INTO public.cards VALUES (316, 34, 'Who was the first ever actor to play "The Doctor" on "Doctor Who"?', 'William Hartnell', 6, 1);
INSERT INTO public.cards VALUES (317, 34, 'What is the name of Chris''s brother in "Everybody Hates Chris"?', 'Drew', 6, 1);
INSERT INTO public.cards VALUES (318, 34, 'What Nickelodeon game show featured a house on the set that the contestants would ransack to find hidden objects?', 'Finders Keepers', 6, 1);
INSERT INTO public.cards VALUES (319, 34, 'In the show "Dragonball Z", what is the name of Cell''s most powerful attack?', 'Solar Kamehameha', 6, 2);
INSERT INTO public.cards VALUES (320, 34, 'Which of the following awards do Matt Stone and Trey Parker NOT have?', 'Oscar', 6, 1);
INSERT INTO public.cards VALUES (321, 35, 'Which of the following bones is not in the leg?', 'Radius', 6, 1);
INSERT INTO public.cards VALUES (322, 35, 'Which of these bones is hardest to break?', 'Femur', 6, 1);
INSERT INTO public.cards VALUES (323, 35, 'What does the letter ''S'' stand for in ''NASA''?', 'Space', 6, 0);
INSERT INTO public.cards VALUES (324, 35, 'What is the hottest planet in the Solar System?', 'Venus', 6, 2);
INSERT INTO public.cards VALUES (325, 35, 'The element involved in making human blood red is which of the following?', 'Iron', 6, 2);
INSERT INTO public.cards VALUES (326, 35, 'The asteroid belt is located between which two planets?', 'Mars and Jupiter', 6, 2);
INSERT INTO public.cards VALUES (327, 35, 'Human cells typically have how many copies of each gene?', '2', 6, 1);
INSERT INTO public.cards VALUES (328, 35, 'What is the standard atomic weight of a Plutonium nucleus?', '244', 6, 1);
INSERT INTO public.cards VALUES (329, 35, 'What is the speed of light in a vacuum?', '299,792,458 m/s', 6, 1);
INSERT INTO public.cards VALUES (330, 35, 'Which of these Elements is a metalloid?', 'Antimony', 6, 1);
INSERT INTO public.cards VALUES (331, 36, 'What is not a wind instrument?', 'Viola', 6, 1);
INSERT INTO public.cards VALUES (332, 36, 'Who is the lead singer of Pearl Jam?', 'Eddie Vedder', 6, 2);
INSERT INTO public.cards VALUES (333, 36, 'Which country does the band Rammstein hail from?', 'Germany', 6, 0);
INSERT INTO public.cards VALUES (334, 36, 'In Mean Girls, who has breasts that tell when it''s raining?', 'Karen Smith', 6, 1);
INSERT INTO public.cards VALUES (336, 36, 'Who is the lead singer of Green Day?', 'Billie Joe Armstrong', 6, 1);
INSERT INTO public.cards VALUES (337, 36, 'Which former boy-band star released hit solo single "Angels" in 1997?', 'Robbie Williams', 6, 1);
INSERT INTO public.cards VALUES (338, 36, 'Who was "Kung Fu Fighting" in 1974?', 'Carl Douglas', 6, 1);
INSERT INTO public.cards VALUES (339, 36, '"Grande Valse" is a phrase from the song "Gran Vals". What is that song segment known as?', 'Nokia Tune', 6, 2);
INSERT INTO public.cards VALUES (410, 43, 'Greenland is a part of which kingdom?', 'Denmark', 7, 2);
INSERT INTO public.cards VALUES (361, 39, 'Which company did Valve cooperate with in the creation of the Vive?', 'HTC', 6, NULL);
INSERT INTO public.cards VALUES (362, 39, 'What does the ''S'' stand for in the abbreviation SIM, as in SIM card? ', 'Subscriber', 6, NULL);
INSERT INTO public.cards VALUES (363, 39, 'What alcoholic drink is made from molasses?', 'Rum', 6, NULL);
INSERT INTO public.cards VALUES (364, 39, 'What type of animal was Harambe, who was shot after a child fell into it''s enclosure at the Cincinnati Zoo?', 'Gorilla', 6, NULL);
INSERT INTO public.cards VALUES (365, 39, 'What is on display in the Madame Tussaud''s museum in London?', 'Wax sculptures', 6, NULL);
INSERT INTO public.cards VALUES (366, 39, 'What do the letters of the fast food chain KFC stand for?', 'Kentucky Fried Chicken', 6, NULL);
INSERT INTO public.cards VALUES (367, 39, 'The likeness of which president is featured on the rare $2 bill of USA currency?', 'Thomas Jefferson', 6, NULL);
INSERT INTO public.cards VALUES (368, 39, 'The Flag of the European Union has how many stars on it?', '12', 6, NULL);
INSERT INTO public.cards VALUES (369, 39, 'How many furlongs are there in a mile?', 'Eight', 6, NULL);
INSERT INTO public.cards VALUES (370, 39, 'What kind of aircraft was developed by Igor Sikorsky in the United States in 1942?', 'Helicopter', 6, NULL);
INSERT INTO public.cards VALUES (342, 37, 'Which of the following car manufacturers had a war named after it?', 'Toyota', 6, 2);
INSERT INTO public.cards VALUES (343, 37, 'Jaguar Cars was previously owned by which car manfacturer?', 'Ford', 6, 1);
INSERT INTO public.cards VALUES (344, 37, 'What UK Train does NOT go over 125MPH?', 'Sprinter', 6, 1);
INSERT INTO public.cards VALUES (345, 37, 'Which car tire manufacturer is famous for its "P Zero" line?', 'Pirelli', 6, 2);
INSERT INTO public.cards VALUES (346, 37, 'What are the cylinder-like parts that pump up and down within the engine?', 'Pistons', 6, 2);
INSERT INTO public.cards VALUES (347, 37, 'The LS7 engine is how many cubic inches?', '427', 6, 2);
INSERT INTO public.cards VALUES (348, 37, 'The LS3 engine is how many cubic inches?', '376', 6, 1);
INSERT INTO public.cards VALUES (349, 37, 'What is the name of Nissan''s most popular electric car?', 'Leaf', 6, 2);
INSERT INTO public.cards VALUES (350, 37, 'What country was the Trabant 601 manufactured in?', 'East Germany', 6, 1);
INSERT INTO public.cards VALUES (351, 38, 'How many spaces are there on a standard Monopoly board?', '40', 6, 1);
INSERT INTO public.cards VALUES (352, 38, 'How many dice are used in the game of Yahtzee?', 'Five', 6, 2);
INSERT INTO public.cards VALUES (353, 38, 'How many pieces are there on the board at the start of a game of chess?', '32', 6, 0);
INSERT INTO public.cards VALUES (355, 38, 'How many dots are on a single die?', '21', 6, 1);
INSERT INTO public.cards VALUES (356, 38, 'Which one of these is not a real game in the Dungeons & Dragons series?', 'Extreme Dungeons & Dragons', 6, 2);
INSERT INTO public.cards VALUES (357, 38, 'In which year was the pen and paper RPG "Deadlands" released?', '1996', 6, 1);
INSERT INTO public.cards VALUES (358, 38, 'When was the board game Twister, released to the public?', 'April 1966', 6, 1);
INSERT INTO public.cards VALUES (359, 38, 'In board games, an additional or ammended rule that applies to a certain group or place is informally known as a "what" rule?', 'House', 6, 1);
INSERT INTO public.cards VALUES (360, 38, 'What is the maximum level you can have in a single class in Dungeons and Dragons (5e)?', '20', 6, 1);
INSERT INTO public.cards VALUES (371, 40, 'Which of the following is not the name of a "Bond Girl"? ', 'Vanessa Kensington', 6, 2);
INSERT INTO public.cards VALUES (372, 40, 'Which of the following was not one of "The Magnificent Seven"?', 'Clint Eastwood', 6, 2);
INSERT INTO public.cards VALUES (373, 40, 'Daniel Radcliffe became a global star in the film industry due to his performance in which film franchise?', 'Harry Potter', 6, 2);
INSERT INTO public.cards VALUES (374, 40, 'What name did Tom Hanks give to his volleyball companion in the film `Cast Away`?', 'Wilson', 6, 2);
INSERT INTO public.cards VALUES (375, 40, 'When was the movie ''Con Air'' released?', '1997', 6, 2);
INSERT INTO public.cards VALUES (376, 40, 'Who played the female lead in the 1933 film "King Kong"?', 'Fay Wray', 6, 2);
INSERT INTO public.cards VALUES (377, 40, 'Who is the main protagonist in, the 1985 film, Back to the Future?', 'Marty McFly', 6, 2);
INSERT INTO public.cards VALUES (378, 40, 'In the movie "Cast Away" the main protagonist''s best friend while on the island is named', 'Wilson', 6, 2);
INSERT INTO public.cards VALUES (379, 40, '"The first rule is: you don''t talk about it" is a reference to which movie?', 'Fight Club', 6, 1);
INSERT INTO public.cards VALUES (381, 41, 'In any programming language, what is the most common way to iterate through an array?', '''For'' loops', 7, 1);
INSERT INTO public.cards VALUES (382, 41, 'What does CPU stand for?', 'Central Processing Unit', 7, 0);
INSERT INTO public.cards VALUES (383, 41, 'What does the Prt Sc button do?', 'Captures what''s on the screen and copies it to your clipboard', 7, 2);
INSERT INTO public.cards VALUES (384, 41, 'What is the code name for the mobile operating system Android 7.0?', 'Nougat', 7, 1);
INSERT INTO public.cards VALUES (385, 41, 'The numbering system with a radix of 16 is more commonly referred to as ', 'Hexidecimal', 7, 0);
INSERT INTO public.cards VALUES (386, 41, 'This mobile OS held the largest market share in 2012.', 'iOS', 7, 1);
INSERT INTO public.cards VALUES (387, 41, 'Which programming language shares its name with an island in Indonesia?', 'Java', 7, 2);
INSERT INTO public.cards VALUES (388, 41, 'How long is an IPv6 address?', '128 bits', 7, 1);
INSERT INTO public.cards VALUES (389, 41, 'In computing, what does LAN stand for?', 'Local Area Network', 7, 0);
INSERT INTO public.cards VALUES (390, 41, 'What language does Node.js use?', 'JavaScript', 7, 1);
INSERT INTO public.cards VALUES (391, 42, 'Which Canadian reggae musician had a 1993 hit with the song ''Informer''?', 'Snow', 7, 2);
INSERT INTO public.cards VALUES (392, 42, 'Who had a 1969 top 5 hit with the song,  ''A Boy Named Sue''?', 'Johnny Cash', 7, 1);
INSERT INTO public.cards VALUES (393, 42, '"Some people call me the space cowboy" is the first line from what song?', 'The Joker', 7, 2);
INSERT INTO public.cards VALUES (394, 42, 'Which rap group released the album "Straight Outta Compton"?', 'N.W.A', 7, 0);
INSERT INTO public.cards VALUES (395, 42, 'How many studio albums have the duo Daft Punk released?', '4', 7, 2);
INSERT INTO public.cards VALUES (396, 42, 'Which of these songs by Skrillex features Fatman Scoop as a side artist?', 'Recess', 7, 1);
INSERT INTO public.cards VALUES (397, 42, 'What collaborative album was released by Kanye West and Jay-Z in 2011?', 'Watch the Throne', 7, 1);
INSERT INTO public.cards VALUES (398, 42, 'Who was featured in the song "Words" by Feint? ', 'Laura Brehm', 7, 0);
INSERT INTO public.cards VALUES (399, 42, 'What was Daft Punk''s first studio album?', 'Homework', 7, 1);
INSERT INTO public.cards VALUES (400, 42, 'Who is the lead singer of Arctic Monkeys?', 'Alex Turner', 7, 2);
INSERT INTO public.cards VALUES (402, 43, 'What is the capital of Indonesia?', 'Jakarta', 7, 0);
INSERT INTO public.cards VALUES (403, 43, 'How many federal states does Germany have?', '16', 7, 1);
INSERT INTO public.cards VALUES (404, 43, 'All of the following are classified as Finno-Ugric languages EXCEPT:', 'Samoyedic', 7, 0);
INSERT INTO public.cards VALUES (405, 43, 'The derisive acronym "PIIGS" refers to which of the following European countries and their economic statuses?', 'Portugal, Ireland, Italy, Greece, Spain', 7, 1);
INSERT INTO public.cards VALUES (406, 43, 'Which of these African countries list "Spanish" as an official language?', 'Equatorial Guinea', 7, 0);
INSERT INTO public.cards VALUES (407, 43, 'The Space Needle is located in which city?', 'Seattle', 7, 1);
INSERT INTO public.cards VALUES (408, 43, 'Which ocean borders the west coast of the United States?', 'Pacific', 7, 1);
INSERT INTO public.cards VALUES (409, 43, 'The longest shared border in the world can be found between which two nations?', 'Canada and the United States', 7, 1);
INSERT INTO public.cards VALUES (441, 47, 'In the show, Doctor Who, what does T.A.R.D.I.S stand for?', 'Time And Relative Dimensions In Space', 7, NULL);
INSERT INTO public.cards VALUES (442, 47, 'Which show is known for the songs "You are a Pirate", "Cooking by the Book" and "We Are Number One"?', 'LazyTown', 7, NULL);
INSERT INTO public.cards VALUES (443, 47, 'In "Breaking Bad", Walter White is a high school teacher diagnosed with which form of cancer?', 'Lung Cancer', 7, NULL);
INSERT INTO public.cards VALUES (444, 47, 'What is the name of the planet that the Doctor from television series "Doctor Who" comes from?', 'Gallifrey', 7, NULL);
INSERT INTO public.cards VALUES (445, 47, 'Who was the first ever actor to play "The Doctor" on "Doctor Who"?', 'William Hartnell', 7, NULL);
INSERT INTO public.cards VALUES (446, 47, 'What NBC sitcom once saw two of its characters try to pitch NBC on a sitcom about nothing?', 'Seinfeld', 7, NULL);
INSERT INTO public.cards VALUES (447, 47, 'What is the name of Chris''s brother in "Everybody Hates Chris"?', 'Drew', 7, NULL);
INSERT INTO public.cards VALUES (448, 47, 'The HBO series "Game of Thrones" is based on which series of books?', 'A Song of Ice and Fire', 7, NULL);
INSERT INTO public.cards VALUES (449, 47, 'In which state of America was the Fresh Prince of Bel-Air born and raised in?', 'Pennsylvania', 7, NULL);
INSERT INTO public.cards VALUES (450, 47, 'What TV show is about a grandfather dragging his grandson around on adventures?', 'Rick & Morty', 7, NULL);
INSERT INTO public.cards VALUES (1, 1, 'Which of the following is the world''s best-selling book?', 'The Lord of the Rings', 3, 2);
INSERT INTO public.cards VALUES (452, 48, 'Which of these companies does NOT manufacture motorcycles?', 'Toyota', 7, 2);
INSERT INTO public.cards VALUES (453, 48, 'Automobiles produced by Telsa Motors operate on which form of energy?', 'Electricity', 7, 1);
INSERT INTO public.cards VALUES (454, 48, 'Which car tire manufacturer is famous for its "P Zero" line?', 'Pirelli', 7, 2);
INSERT INTO public.cards VALUES (455, 48, 'What are the cylinder-like parts that pump up and down within the engine?', 'Pistons', 7, 1);
INSERT INTO public.cards VALUES (456, 48, 'The LS1 engine is how many cubic inches?', '346', 7, 1);
INSERT INTO public.cards VALUES (457, 48, 'The LS2 engine is how many cubic inches?', '364', 7, 1);
INSERT INTO public.cards VALUES (458, 48, 'The LS7 engine is how many cubic inches?', '427', 7, 2);
INSERT INTO public.cards VALUES (459, 48, 'What is the name of Nissan''s most popular electric car?', 'Leaf', 7, 2);
INSERT INTO public.cards VALUES (460, 48, 'What is the fastest road legal car in the world?', 'Koenigsegg Agera RS', 7, 1);
INSERT INTO public.cards VALUES (412, 44, 'By what name is Carlos Estevez better known? ', 'Charlie Sheen', 7, 0);
INSERT INTO public.cards VALUES (413, 44, 'Which actress married Michael Douglas in 2000?', 'Catherine Zeta-Jones', 7, 1);
INSERT INTO public.cards VALUES (414, 44, 'What was the cause of Marilyn Monroes suicide?', 'Drug Overdose', 7, 2);
INSERT INTO public.cards VALUES (415, 44, 'Gwyneth Paltrow has a daughter named...?', 'Apple', 7, 0);
INSERT INTO public.cards VALUES (416, 44, 'Which celebrity announced his presidency in 2015?', 'Kanye West', 7, 1);
INSERT INTO public.cards VALUES (417, 44, 'Aubrey Graham is better known as', 'Drake', 7, 1);
INSERT INTO public.cards VALUES (418, 44, 'Neil Hamburger is played by which comedian?', 'Gregg Turkington', 7, 1);
INSERT INTO public.cards VALUES (419, 44, 'By which name is Ramon Estevez better known as?', 'Martin Sheen', 7, 1);
INSERT INTO public.cards VALUES (420, 44, 'What was James Coburn''s last film role before his death?', 'American Gun', 7, 2);
INSERT INTO public.cards VALUES (421, 45, 'George Orwell wrote this book, which is often considered a statement on government oversight.', '1984', 7, 2);
INSERT INTO public.cards VALUES (422, 45, 'Which famous book is sub-titled ''The Modern Prometheus''?', 'Frankenstein', 7, 1);
INSERT INTO public.cards VALUES (423, 45, 'How many Harry Potter books are there?', '7', 7, 2);
INSERT INTO public.cards VALUES (424, 45, 'Under what pseudonym did Stephen King publish five novels between 1977 and 1984?', 'Richard Bachman', 7, 1);
INSERT INTO public.cards VALUES (425, 45, 'What''s Harry Potter''s dad''s name?', 'James Potter', 7, 2);
INSERT INTO public.cards VALUES (426, 45, 'Who was the author of the 1954 novel, "Lord of the Flies"?', 'William Golding', 7, 1);
INSERT INTO public.cards VALUES (427, 45, 'What is the name of the protagonist of J.D. Salinger''s novel Catcher in the Rye?', 'Holden Caulfield', 7, 2);
INSERT INTO public.cards VALUES (428, 45, 'What''s the second book in George R. R. Martin''s ''A Song of Ice and Fire'' series?', 'A Clash of Kings', 7, 2);
INSERT INTO public.cards VALUES (429, 45, 'What was the first ever entry written for the SCP Foundation collaborative writing project?', 'SCP-173', 7, 1);
INSERT INTO public.cards VALUES (430, 45, 'Which is NOT a book in the Harry Potter Series?', 'The House Elf', 7, 1);
INSERT INTO public.cards VALUES (431, 46, 'How many planets are in our Solar System?', 'Eight', 7, 1);
INSERT INTO public.cards VALUES (432, 46, 'What is the chemical makeup of water?', 'H20', 7, 0);
INSERT INTO public.cards VALUES (433, 46, 'What was the name of the first artificial Earth satellite, launched by the Soviet Union in 1957?', 'Sputnik 1', 7, 1);
INSERT INTO public.cards VALUES (434, 46, 'The asteroid belt is located between which two planets?', 'Mars and Jupiter', 7, 1);
INSERT INTO public.cards VALUES (435, 46, 'Human cells typically have how many copies of each gene?', '2', 7, 2);
INSERT INTO public.cards VALUES (436, 46, 'Which element has the highest melting point?', 'Carbon', 7, 1);
INSERT INTO public.cards VALUES (437, 46, '71% of the Earth''s surface is made up of', 'Water', 7, 1);
INSERT INTO public.cards VALUES (439, 46, 'What is the unit of electrical resistance?', 'Ohm', 7, 1);
INSERT INTO public.cards VALUES (440, 46, 'Which of these Elements is a metalloid?', 'Antimony', 7, 1);
INSERT INTO public.cards VALUES (461, 49, 'What is the best selling album of all time from 1976 to 2018?', 'Thriller', 7, 0);
INSERT INTO public.cards VALUES (462, 49, 'The "K" in "K-Pop" stands for which word?', 'Korean', 7, 1);
INSERT INTO public.cards VALUES (463, 49, 'Which of these is the name of a song by Tears for Fears?', 'Shout', 7, 0);
INSERT INTO public.cards VALUES (464, 49, 'Kanye West at 2009 VMA''s interrupted which celebrity?', 'Taylor Swift', 7, 2);
INSERT INTO public.cards VALUES (465, 49, 'Who is the lead singer of Green Day?', 'Billie Joe Armstrong', 7, 1);
INSERT INTO public.cards VALUES (466, 49, 'Which song on Daft Punk''s "Random Access Memories" features Pharrell Williams?', 'Get Lucky', 7, 1);
INSERT INTO public.cards VALUES (467, 49, 'When was Gangnam Style uploaded to YouTube?', '2012', 7, 0);
INSERT INTO public.cards VALUES (469, 49, 'Who was "Kung Fu Fighting" in 1974?', 'Carl Douglas', 7, 1);
INSERT INTO public.cards VALUES (470, 49, '"Grande Valse" is a phrase from the song "Gran Vals". What is that song segment known as?', 'Nokia Tune', 7, 1);
INSERT INTO public.cards VALUES (471, 50, 'What is the fastest  land animal?', 'Cheetah', 7, 2);
INSERT INTO public.cards VALUES (472, 50, 'What is the scientific name for modern day humans?', 'Homo Sapiens', 7, 1);
INSERT INTO public.cards VALUES (473, 50, 'Hippocampus is the Latin name for which marine creature?', 'Seahorse', 7, 1);
INSERT INTO public.cards VALUES (474, 50, 'How many legs do butterflies have?', '6', 7, 2);
INSERT INTO public.cards VALUES (475, 50, 'What is Grumpy Cat''s real name?', 'Tardar Sauce', 7, 1);
INSERT INTO public.cards VALUES (476, 50, 'What is the collective noun for a group of crows?', 'Murder', 7, 2);
INSERT INTO public.cards VALUES (477, 50, 'By definition, where does an abyssopelagic animal live?', 'At the bottom of the ocean', 7, 2);
INSERT INTO public.cards VALUES (478, 50, 'What colour is the female blackbird?', 'Brown', 7, 2);
INSERT INTO public.cards VALUES (479, 50, 'How many teeth does an adult rabbit have?', '28', 7, 1);
INSERT INTO public.cards VALUES (480, 50, 'What is the name of a rabbit''s abode?', 'Burrow', 7, 2);
INSERT INTO public.cards VALUES (3, 1, 'Which famous spy novelist wrote the childrens'' story "Chitty-Chitty-Bang-Bang"?', 'Ian Fleming', 3, 0);
INSERT INTO public.cards VALUES (21, 3, 'During WWII, in 1945, the United States dropped atomic bombs on the two Japanese cities of Hiroshima and what other city?', 'Nagasaki', 3, 2);
INSERT INTO public.cards VALUES (43, 5, 'In DuckTales, what is the name of the city where all the main characters live?', 'Duckburg', 3, 1);
INSERT INTO public.cards VALUES (64, 7, 'What machine element is located in the center of fidget spinners?', 'Bearings', 3, 2);
INSERT INTO public.cards VALUES (70, 7, 'Which country has the union jack in its flag?', 'New Zealand', 3, 2);
INSERT INTO public.cards VALUES (488, 51, 'What is a constructor?', 'It is a special method that is used to initialize objects. The constructor is called when an object of a class is created.', 4, 2);
INSERT INTO public.cards VALUES (484, 9, 'Which pandemic plays an important role in the musical Rent?', 'HIV/ AIDS', 3, 2);
INSERT INTO public.cards VALUES (485, 9, 'Who was the first black person on Broadway?', 'Bert Williams', 3, 2);
INSERT INTO public.cards VALUES (486, 9, 'Who was the first POC who broke racial barriers with their role in Les Miserables?', 'Leah Salonga', 3, 2);
INSERT INTO public.cards VALUES (482, 8, 'Which of the following Broadway musicals features music by Andrew Lloyd Webber and lyrics by Charles Hart? The Phantom of the Opera, Les Miserables, The Lion King, or Wicked?', 'Phantom of the Opera', 3, 1);
INSERT INTO public.cards VALUES (483, 8, 'Which Broadway musical featured a helicopter onstage?', 'Miss Saigon', 3, 2);
INSERT INTO public.cards VALUES (481, 8, 'In which Broadway musical does Jack sing “There are giants in the sky”?', 'Into the Woods', 3, 1);
INSERT INTO public.cards VALUES (81, 11, 'Which Apollo mission was the first one to land on the Moon?', 'Apollo 11', 4, 2);
INSERT INTO public.cards VALUES (88, 11, 'The biggest distinction between a eukaryotic cell and a prokaryotic cell is:', 'The presence or absence of a nucleus', 4, 2);
INSERT INTO public.cards VALUES (101, 13, 'What breed of dog was Marley in the film "Marley & Me" (2008)?', 'Labrador Retriever', 4, 1);
INSERT INTO public.cards VALUES (132, 16, 'Which English football club has the nickname ''The Foxes''?', 'Leicester City', 4, 1);
INSERT INTO public.cards VALUES (141, 17, 'What is the fastest  land animal?', 'Cheetah', 4, 1);
INSERT INTO public.cards VALUES (181, 21, 'Which Italian city is home of the car manufacturer ''Fiat''?', 'Turin', 5, 1);
INSERT INTO public.cards VALUES (185, 21, 'Which car tire manufacturer is famous for its "Eagle" brand of tires, and is the official tire supplier of NASCAR?', 'Goodyear', 5, 0);
INSERT INTO public.cards VALUES (231, 26, 'In any programming language, what is the most common way to iterate through an array?', '''For'' loops', 5, 2);
INSERT INTO public.cards VALUES (213, 24, 'The Kākāpō is a large, flightless, nocturnal parrot native to which country?', 'New Zealand', 5, 1);
INSERT INTO public.cards VALUES (285, 31, 'In Baseball, how many times does the ball have to be pitched outside of the strike zone before the batter is walked?', '4', 6, 1);
INSERT INTO public.cards VALUES (306, 33, 'The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:', 'HD Graphics 500', 6, 0);
INSERT INTO public.cards VALUES (335, 36, 'In 2006, which band released their debut album "A Fever You Can''t Sweat Out"?', 'Panic! At the Disco', 6, 1);
INSERT INTO public.cards VALUES (340, 36, 'Which year was the album "Year of the Snitch" by Death Grips released?', '2018', 6, 0);
INSERT INTO public.cards VALUES (341, 37, 'Which Italian city is home of the car manufacturer ''Fiat''?', 'Turin', 6, 1);
INSERT INTO public.cards VALUES (354, 38, 'On a standard Monopoly board, which square is diagonally opposite ''Go''? ', 'Free Parking', 6, 1);
INSERT INTO public.cards VALUES (380, 40, 'What historical time period was the center of the Assassin’s Creed movie (2016)?', 'Spanish Inquisition', 6, 1);
INSERT INTO public.cards VALUES (451, 48, 'Where are the cars of the brand "Ferrari" manufactured?', 'Italy', 7, 1);
INSERT INTO public.cards VALUES (401, 43, 'Which city is the capital of the United States of America?', 'Washington D.C', 7, 1);
INSERT INTO public.cards VALUES (411, 44, 'Named after a character he played in a 1969 film, what is the name of the ski resort in Utah that Robert Redford bought in 1968?', 'Sundance', 7, 2);
INSERT INTO public.cards VALUES (438, 46, 'What does LASER stand for?', 'Light amplification by stimulated emission of radiation', 7, 0);
INSERT INTO public.cards VALUES (468, 49, 'Which punk rock band released hit songs such as "Californication", "Can''t Stop" and "Under the Bridge"?', 'Red Hot Chilli Peppers', 7, 1);
INSERT INTO public.cards VALUES (505, 53, 'What is the most frequently sold item at Walmart?', 'Banana', 3, 0);
INSERT INTO public.cards VALUES (506, 53, 'What is Jenny''s phone number in the popular ''80''s song?', '867-5309', 3, 0);
INSERT INTO public.cards VALUES (507, 53, 'What movie was Eye of the Tiger written for?', 'Rocky III', 3, 0);
INSERT INTO public.cards VALUES (489, 51, 'What is an object in Java?', 'an instance of a class', 4, 0);
INSERT INTO public.cards VALUES (490, 51, 'What is method overloading?', 'a feature that allows a class to have more than one method with the same name, but with different parameters.', 4, 1);
INSERT INTO public.cards VALUES (492, 51, 'Who are the greatest Java instructors in America?', 'Tom & Yoav <3', 4, 2);
INSERT INTO public.cards VALUES (491, 51, 'What is the main difference between a list & an array?', 'Array: size should be given at the time of array declaration... List: size is dynamic and not required', 4, 1);
INSERT INTO public.cards VALUES (493, 52, 'Grant Gustin plays which superhero on the CW show of the same name?', 'The Flash', 4, 0);
INSERT INTO public.cards VALUES (494, 52, 'The "Psycho" series of videos on YouTube was created by which of the following?', 'RiDGiD STUDiOS', 4, 0);
INSERT INTO public.cards VALUES (495, 52, 'In Game of Thrones, what is Littlefinger''s real name?', 'Petyr Baelish', 4, 0);
INSERT INTO public.cards VALUES (496, 52, 'In the television show Breaking Bad, what is the street name of Walter and Jesse''s notorious product?', 'Blue Sky', 4, 0);
INSERT INTO public.cards VALUES (497, 52, 'In the show "Tengen Toppa Gurren Lagann" what is the name of the character who force everyone to live underground?', 'Lordgenome', 4, 0);
INSERT INTO public.cards VALUES (498, 52, 'Which show is known for the songs "You are a Pirate", "Cooking by the Book" and "We Are Number One"?', 'LazyTown', 4, 0);
INSERT INTO public.cards VALUES (499, 52, 'Who won Big Brother 2014 UK?', 'Helen Wood', 4, 0);
INSERT INTO public.cards VALUES (500, 52, 'Which of these Disney shows is classified as an anime?', 'Stitch!', 4, 0);
INSERT INTO public.cards VALUES (501, 52, 'How many seasons did the Sci-Fi television show "Stargate Universe" have?', '2', 4, 0);
INSERT INTO public.cards VALUES (502, 52, 'What Nickelodeon game show featured a house on the set that the contestants would ransack to find hidden objects?', 'Finders Keepers', 4, 0);
INSERT INTO public.cards VALUES (487, 51, 'What are the four basic principals of  OOP?', 'Abstraction, encapsulation, polymorphism, and inheritance', 4, 1);
INSERT INTO public.cards VALUES (504, 53, 'Which country produces the most coffee in the world?', 'Brazil', 3, 0);
INSERT INTO public.cards VALUES (508, 53, 'What has a head and a tail but no body?', 'A coin', 3, 0);


--
-- TOC entry 2884 (class 0 OID 42695)
-- Dependencies: 209
-- Data for Name: deck_tag; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2880 (class 0 OID 42660)
-- Dependencies: 205
-- Data for Name: decks; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2888 (class 0 OID 42733)
-- Dependencies: 213
-- Data for Name: study_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.study_session VALUES (1, 3, 1, 10, 5, 3, 5, 2, 55, 50);
INSERT INTO public.study_session VALUES (2, 3, 2, 10, 7, 1, 8, 1, 50, 70);
INSERT INTO public.study_session VALUES (3, 3, 3, 10, 9, 6, 4, 0, 80, 90);
INSERT INTO public.study_session VALUES (4, 3, 4, 10, 9, 2, 6, 2, 50, 90);
INSERT INTO public.study_session VALUES (5, 3, 5, 10, 7, 3, 4, 3, 50, 70);
INSERT INTO public.study_session VALUES (6, 3, 6, 10, 4, 1, 6, 3, 40, 40);
INSERT INTO public.study_session VALUES (7, 3, 7, 10, 6, 3, 5, 2, 55, 60);
INSERT INTO public.study_session VALUES (8, 3, 9, 3, 3, 3, 0, 0, 100, 100);
INSERT INTO public.study_session VALUES (9, 3, 8, 3, 2, 1, 2, 0, 67, 67);
INSERT INTO public.study_session VALUES (10, 4, 11, 10, 10, 10, 0, 0, 100, 100);
INSERT INTO public.study_session VALUES (11, 4, 12, 10, 5, 2, 5, 3, 45, 50);
INSERT INTO public.study_session VALUES (12, 4, 14, 10, 5, 2, 6, 2, 50, 50);
INSERT INTO public.study_session VALUES (13, 4, 13, 10, 7, 3, 5, 2, 55, 70);
INSERT INTO public.study_session VALUES (14, 4, 15, 10, 5, 4, 4, 2, 60, 50);
INSERT INTO public.study_session VALUES (15, 4, 16, 10, 9, 3, 5, 2, 55, 90);
INSERT INTO public.study_session VALUES (16, 4, 17, 10, 3, 2, 5, 3, 45, 30);
INSERT INTO public.study_session VALUES (17, 5, 21, 10, 10, 4, 5, 1, 65, 100);
INSERT INTO public.study_session VALUES (18, 5, 22, 10, 6, 4, 5, 1, 65, 60);
INSERT INTO public.study_session VALUES (19, 5, 23, 10, 8, 4, 4, 2, 60, 80);
INSERT INTO public.study_session VALUES (20, 5, 24, 10, 8, 1, 6, 3, 40, 80);
INSERT INTO public.study_session VALUES (21, 5, 25, 10, 9, 3, 6, 1, 60, 90);
INSERT INTO public.study_session VALUES (22, 5, 26, 10, 8, 3, 5, 2, 55, 80);
INSERT INTO public.study_session VALUES (23, 5, 29, 10, 7, 2, 6, 2, 50, 70);
INSERT INTO public.study_session VALUES (24, 5, 24, 10, 9, 6, 3, 1, 75, 90);
INSERT INTO public.study_session VALUES (25, 5, 27, 10, 10, 10, 0, 0, 100, 100);
INSERT INTO public.study_session VALUES (26, 5, 30, 10, 0, 0, 0, 10, 0, 0);
INSERT INTO public.study_session VALUES (27, 4, 20, 10, 10, 10, 0, 0, 100, 100);
INSERT INTO public.study_session VALUES (28, 6, 31, 10, 7, 4, 5, 1, 65, 70);
INSERT INTO public.study_session VALUES (29, 6, 32, 10, 8, 3, 5, 2, 55, 80);
INSERT INTO public.study_session VALUES (30, 6, 33, 10, 2, 1, 2, 7, 20, 20);
INSERT INTO public.study_session VALUES (31, 6, 34, 10, 8, 2, 7, 1, 55, 80);
INSERT INTO public.study_session VALUES (32, 6, 35, 10, 4, 3, 6, 1, 60, 40);
INSERT INTO public.study_session VALUES (33, 6, 36, 10, 4, 2, 6, 2, 50, 40);
INSERT INTO public.study_session VALUES (34, 6, 37, 10, 9, 5, 5, 0, 75, 90);
INSERT INTO public.study_session VALUES (35, 6, 38, 10, 9, 2, 7, 1, 55, 90);
INSERT INTO public.study_session VALUES (36, 6, 40, 10, 10, 8, 2, 0, 90, 100);
INSERT INTO public.study_session VALUES (37, 7, 48, 10, 8, 4, 6, 0, 70, 80);
INSERT INTO public.study_session VALUES (38, 7, 41, 10, 7, 2, 5, 3, 45, 70);
INSERT INTO public.study_session VALUES (39, 7, 42, 10, 8, 4, 4, 2, 60, 80);
INSERT INTO public.study_session VALUES (40, 7, 43, 10, 5, 1, 6, 3, 40, 50);
INSERT INTO public.study_session VALUES (41, 7, 44, 10, 3, 3, 5, 2, 55, 30);
INSERT INTO public.study_session VALUES (42, 7, 45, 10, 8, 5, 5, 0, 75, 80);
INSERT INTO public.study_session VALUES (43, 7, 46, 10, 8, 1, 7, 2, 45, 80);
INSERT INTO public.study_session VALUES (44, 7, 49, 10, 5, 1, 6, 3, 40, 50);
INSERT INTO public.study_session VALUES (45, 7, 50, 10, 10, 6, 4, 0, 80, 100);
INSERT INTO public.study_session VALUES (46, 4, 51, 6, 6, 5, 0, 1, 83, 100);
INSERT INTO public.study_session VALUES (47, 4, 51, 6, 6, 2, 3, 1, 58, 100);


--
-- TOC entry 2883 (class 0 OID 42689)
-- Dependencies: 208
-- Data for Name: tags; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2881 (class 0 OID 42672)
-- Dependencies: 206
-- Data for Name: user_deck; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 2878 (class 0 OID 42650)
-- Dependencies: 203
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--




COMMIT TRANSACTION;